feat(db): - add restore job

diff --git a/db/restore-backup.yaml b/db/restore-backup.yaml
--- a/db/restore-backup.yaml
+++ b/db/restore-backup.yaml
@@ -12,13 +12,18 @@ spec:
             - /bin/sh
             - -c
             - |
-              echo "Restoring database from backup file $BACKUP_FILE..."
-              export PGPASSWORD=$POSTGRES_PASSWORD
-              pg_restore \
-              -h $DB_HOST \
-              -U $POSTGRES_USER \
-              -d $POSTGRES_DB \
-              -f /backup/$BACKUP_FILE
+              if [ -f "$BACKUP_FILE" ]; then
+                echo "Restoring database from backup file $BACKUP_FILE..."
+                export PGPASSWORD=$POSTGRES_PASSWORD
+                pg_restore \
+                -h $DB_HOST \
+                -U $POSTGRES_USER \
+                -d $POSTGRES_DB \
+                -f /backup/$BACKUP_FILE
+              else
+                echo "Backup file not found: $BACKUP_FILE"
+                exit 1
+              fi
           env:
             - name: BACKUP_FILE
               value: "2025-01-20/backup.sql"
